config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]
  resources :wikis
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  get "users/:id", :controller => "users", :action => "show"

  post '/downgrade_to_standard' => 'downgrades#downgrade_to_standard', as: :downgrade_to_standard

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
    has_many :collaborators, dependent: :destroy
    has_many :wikis, through: :collaborators
    has_many :wikis, dependent: :destroy
    before_save { self.role ||= :standard }
    enum role: [:standard, :admin, :premium]
    scope :all_except, ->(user) { where.not(id: user) }
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  validates :user, presence: true
  validates :title, presence: true
  validates :body, presence: true
  default_scope { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
require 'amount'
class ChargesController < ApplicationController
  before_action :authorize_user

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    current_user.premium!
    redirect_to wikis_path # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

private
  def authorize_user
    unless current_user.standard?
      flash[:alert] = "You must be a standard user to do that."
      redirect_to root_path
    end
  end

end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController

  def downgrade_to_standard
    if current_user.premium?
      current_user.standard!
    end

    current_user.wikis.each do |wiki|
      wiki.private = false
      wiki.save
    end

    redirect_to :back
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    collaborations = Collaborator.where(user_id: @user.id)
    @collab_wikis = Wiki.where(id: collaborations.pluck(:wiki_id))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authorize_user, except: [:index, :show, :new, :create, :edit, :update]
  before_action :user_is_authorized_to_edit_private_wiki, only: [:show, :edit, :update]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user


    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all_except(current_user)
  end
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    #only let premium owner or admin change the private settings and collaborators
    if current_user == @wiki.user || current_user.admin?
      @wiki.private = params[:wiki][:private]
      @wiki.user_ids = params[:collaborators]
    end

    if @wiki.private == false
      @wiki.user_ids = nil
    end

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
     flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
     redirect_to wikis_path
    else
     flash.now[:alert] = "There was an error deleting the wiki."
     render :show
    end
  end

private
  def authorize_user
    wiki = Wiki.find(params[:id])
    unless current_user == wiki.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to wikis_path
    end
  end

  def user_is_authorized_to_edit_private_wiki
    wiki = Wiki.find(params[:id])
    if !(current_user == wiki.user || current_user.admin? || wiki.users.include?(current_user)) && wiki.private == true
      flash[:alert] = "You must be a collaborator to do that."
      redirect_to wikis_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:          false,
      no_links:             false,
      hard_wrap:            true,
      link_attributes:      { rel: 'nofollow', target: "_blank" },
      space_after_headers:  true,
      fenced_code_blocks:   true
    }

    extensions = {
      autolink:                     true,
      superscript:                  true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrades_helper.rb
module DowngradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wiki?(wiki)
    current_user && (current_user == wiki.user || current_user.admin?)
  end
  def user_is_authorized_for_private_button?(wiki)
    current_user.admin? || (current_user.premium? && current_user == wiki.user) || (current_user.premium? && current_page?(new_wiki_path(wiki)))
  end
  def user_is_authorized_to_view_collaborators?(wiki)
    current_uri = request.env['PATH_INFO']
    ((wiki.user == current_user && current_user.premium?) || current_user.admin?) && (!(current_page?(new_wiki_path) ||  current_uri == "/wikis"))
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
  data-key="<%= @stripe_btn_data[:key] %>"
  data-amount="<%= @stripe_btn_data[:amount] %>"
  data-description="<%= @stripe_btn_data[:description] %>"
  data-bitcoin="true"
  data-email= "<%= current_user.email %>">
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skatepedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

    <div class="pull-right">
      <% if user_signed_in? %>
          Signed in as: <strong><%= link_to "#{current_user.email}", user_path(current_user.id), class: 'username' %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <div>
         <ul class="nav nav-tabs">
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "Wikis", wikis_path %></li>
         </ul>
      </div>
    <% end %>


    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Profile</h1>
<h3><%="#{@user.email}" %></h3>
<h2>Wikis</h2>
<% if @user == current_user %>
  <%= link_to "New", new_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<% @user.wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
          <%if wiki.private? %>
          <%= "(Private)" %>
          <% end %>
        </h4>
        <h5 class="media-heading">
          Created by <%= wiki.user.email %>
        </h5>
      </div>
    </div>
<% end %>
<% if (@collab_wikis.length > 0 && @user == current_user) || (@collab_wikis.length > 0 && current_user.admin?) %>
  <h2>Collaborations</h2>
  <% @collab_wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
            <%if wiki.private? %>
            <%= "(Private)" %>
            <% end %>
          </h4>
          <h5 class="media-heading">
            Created by <%= link_to "#{wiki.user.email}", user_path(wiki.user.id), class: 'username' %>
          </h5>
        </div>
      </div>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Feel free to write/edit/create anything skateboarding.</p>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <div id="epiceditor" class = "edit-text-area">
      <%= f.text_area :body, rows: 7, class: 'form-control' %>
    </div>
  <% end %>
  <% if user_is_authorized_for_private_button?(wiki) %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private, id: "private" %> Private
      <% end %>
    </div>
  <% end %>

  <% if user_is_authorized_to_view_collaborators?(wiki) %>
    <div class="form-group">
      <div class="collaborators">
        <h6> Add Collaborators</h6>
        <% @users.each do |user| %>
          <div class="user">
          <%= check_box_tag "collaborators[]", user.id, @wiki.user_ids.include?(user.id) %>
          <%= user.email %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>1. Make Sure the Topic is Original.</li>
       <li>2. Topic should relate to skateboarding.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>

<%= javascript_include_tag 'wiki/app.js', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'wiki/epiceditor', 'data-turbolinks-track' => true %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New", new_wiki_path(@wiki), class: 'btn btn-success' %>

<% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
          <%if wiki.private? %>
          <%= "(Private)" %>
          <% end %>
        </h4>
        <h5 class="media-heading">
          Created by <%= link_to "#{wiki.user.email}", user_path(wiki.user.id), class: 'username' %>
        </h5>
      </div>
    </div>
<% end %>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wiki</p>
     <ul>
       <li>1. Make Sure the Topic is Original.</li>
       <li>2. Topic should relate to skateboarding.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>

<%= javascript_include_tag 'wiki/epiceditor', 'data-turbolinks-track' => true %>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %>
  <%if @wiki.private? %>
    <%= "(Private)" %>
  <% end %>
</h1>

<h5 class="media-heading">
Created by <%= link_to "#{@wiki.user.email}", user_path(@wiki.user.id), class: 'username' %>
</h5>

<%if @wiki.private? %>
  <h5>
    Collaborators:
    <% @wiki.users.each do |user|%>
      <i> <%= link_to "#{user.email}", user_path(user.id), class: 'username' %> </i>
    <% end %>
  </h5>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% if user_is_authorized_for_wiki?(@wiki) %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  <% end %>
  </div>
</div>